version: "2.4"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hiro
      POSTGRES_PASSWORD: "password"
    volumes:
      - "db:/var/lib/postgresql/data"
volumes:
  db:
    driver: local
