// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Application application
//
// swagger:model Application
type Application struct {

	// The applications allowed grant types
	// Required: true
	AllowedGrants []string `json:"allowed_grants"`

	// The application client id used for oauth grants
	// Read Only: true
	ClientID string `json:"client_id,omitempty"`

	// The application client secret used for oauth grants
	// Read Only: true
	ClientSecret string `json:"client_secret,omitempty"`

	// The application description
	Description string `json:"description,omitempty"`

	// This is an array of the application's allowed login uris. These are checked
	// in the `/authorize` path to ensure the login redirect is allowed by the application.
	//
	// This path on redirect will receive the following query parameters:
	//   - `auth_request`: An encoded and signed request value to be forwarded with the login post.
	//
	LoginUris []string `json:"login_uris"`

	// This is an array of the application's allowed logout uris. These are checked
	// in the `/logout` path to ensure the logout redirect is allowed by the application.
	//
	LogoutUris []string `json:"logout_uris"`

	// The application name
	// Required: true
	Name string `json:"name"`

	// The application's authorized permissions
	Permissions []string `json:"permissions"`

	// This is an array of the application's allowed redirect uris. These are checked
	// in the `/login` path to ensure the redirect is allowed by the application.
	//
	// This path on redirect will receive the following query parameters:
	//   - `code`: A signed authorization code that can be passed to the `/token` path.
	//
	RedirectUris []string `json:"redirect_uris"`

	// The lifetime for identity tokens in seconds, provided the call requested the
	// `openid` scopes.
	//
	TokenLifetime int64 `json:"token_lifetime,omitempty"`

	// The application type
	// Enum: [web native machine]
	Type string `json:"type,omitempty"`

	// The application creation date
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// The application id
	ID string `json:"id,omitempty"`

	// The last update date
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *Application) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		AllowedGrants []string `json:"allowed_grants"`

		ClientID string `json:"client_id,omitempty"`

		ClientSecret string `json:"client_secret,omitempty"`

		Description string `json:"description,omitempty"`

		LoginUris []string `json:"login_uris"`

		LogoutUris []string `json:"logout_uris"`

		Name string `json:"name"`

		Permissions []string `json:"permissions"`

		RedirectUris []string `json:"redirect_uris"`

		TokenLifetime int64 `json:"token_lifetime,omitempty"`

		Type string `json:"type,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	m.AllowedGrants = dataAO0.AllowedGrants

	m.ClientID = dataAO0.ClientID

	m.ClientSecret = dataAO0.ClientSecret

	m.Description = dataAO0.Description

	m.LoginUris = dataAO0.LoginUris

	m.LogoutUris = dataAO0.LogoutUris

	m.Name = dataAO0.Name

	m.Permissions = dataAO0.Permissions

	m.RedirectUris = dataAO0.RedirectUris

	m.TokenLifetime = dataAO0.TokenLifetime

	m.Type = dataAO0.Type

	// AO1
	var dataAO1 struct {
		CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

		ID string `json:"id,omitempty"`

		UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.CreatedAt = dataAO1.CreatedAt

	m.ID = dataAO1.ID

	m.UpdatedAt = dataAO1.UpdatedAt

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m Application) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	var dataAO0 struct {
		AllowedGrants []string `json:"allowed_grants"`

		ClientID string `json:"client_id,omitempty"`

		ClientSecret string `json:"client_secret,omitempty"`

		Description string `json:"description,omitempty"`

		LoginUris []string `json:"login_uris"`

		LogoutUris []string `json:"logout_uris"`

		Name string `json:"name"`

		Permissions []string `json:"permissions"`

		RedirectUris []string `json:"redirect_uris"`

		TokenLifetime int64 `json:"token_lifetime,omitempty"`

		Type string `json:"type,omitempty"`
	}

	dataAO0.AllowedGrants = m.AllowedGrants

	dataAO0.ClientID = m.ClientID

	dataAO0.ClientSecret = m.ClientSecret

	dataAO0.Description = m.Description

	dataAO0.LoginUris = m.LoginUris

	dataAO0.LogoutUris = m.LogoutUris

	dataAO0.Name = m.Name

	dataAO0.Permissions = m.Permissions

	dataAO0.RedirectUris = m.RedirectUris

	dataAO0.TokenLifetime = m.TokenLifetime

	dataAO0.Type = m.Type

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)
	var dataAO1 struct {
		CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

		ID string `json:"id,omitempty"`

		UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`
	}

	dataAO1.CreatedAt = m.CreatedAt

	dataAO1.ID = m.ID

	dataAO1.UpdatedAt = m.UpdatedAt

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this application
func (m *Application) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAllowedGrants(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var applicationAllowedGrantsItemsEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["authorization_code","client_credentials","refresh_token"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		applicationAllowedGrantsItemsEnum = append(applicationAllowedGrantsItemsEnum, v)
	}
}

func (m *Application) validateAllowedGrantsItemsEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, applicationAllowedGrantsItemsEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Application) validateAllowedGrants(formats strfmt.Registry) error {

	if err := validate.Required("allowed_grants", "body", m.AllowedGrants); err != nil {
		return err
	}

	for i := 0; i < len(m.AllowedGrants); i++ {

		// value enum
		if err := m.validateAllowedGrantsItemsEnum("allowed_grants"+"."+strconv.Itoa(i), "body", m.AllowedGrants[i]); err != nil {
			return err
		}

	}

	return nil
}

func (m *Application) validateName(formats strfmt.Registry) error {

	if err := validate.RequiredString("name", "body", string(m.Name)); err != nil {
		return err
	}

	return nil
}

var applicationTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["web","native","machine"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		applicationTypeTypePropEnum = append(applicationTypeTypePropEnum, v)
	}
}

// property enum
func (m *Application) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, applicationTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Application) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

func (m *Application) validateCreatedAt(formats strfmt.Registry) error {

	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("created_at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Application) validateUpdatedAt(formats strfmt.Registry) error {

	if swag.IsZero(m.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("updated_at", "body", "date-time", m.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Application) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Application) UnmarshalBinary(b []byte) error {
	var res Application
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
