// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"encoding/json"
	"io"
	"io/ioutil"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// Geometry A geoJSON geometry
//
// swagger:discriminator Geometry type
type Geometry interface {
	runtime.Validatable

	// The geometry type
	// Required: true
	// Enum: [Point LineString Polygon MultiPoint MultiLineString MultiPolygon]
	Type() string
	SetType(string)

	// AdditionalProperties in base type shoud be handled just like regular properties
	// At this moment, the base type property is pushed down to the subtype
}

type geometry struct {
	typeField string
}

// Type gets the type of this polymorphic type
func (m *geometry) Type() string {
	return "Geometry"
}

// SetType sets the type of this polymorphic type
func (m *geometry) SetType(val string) {
}

// UnmarshalGeometrySlice unmarshals polymorphic slices of Geometry
func UnmarshalGeometrySlice(reader io.Reader, consumer runtime.Consumer) ([]Geometry, error) {
	var elements []json.RawMessage
	if err := consumer.Consume(reader, &elements); err != nil {
		return nil, err
	}

	var result []Geometry
	for _, element := range elements {
		obj, err := unmarshalGeometry(element, consumer)
		if err != nil {
			return nil, err
		}
		result = append(result, obj)
	}
	return result, nil
}

// UnmarshalGeometry unmarshals polymorphic Geometry
func UnmarshalGeometry(reader io.Reader, consumer runtime.Consumer) (Geometry, error) {
	// we need to read this twice, so first into a buffer
	data, err := ioutil.ReadAll(reader)
	if err != nil {
		return nil, err
	}
	return unmarshalGeometry(data, consumer)
}

func unmarshalGeometry(data []byte, consumer runtime.Consumer) (Geometry, error) {
	buf := bytes.NewBuffer(data)
	buf2 := bytes.NewBuffer(data)

	// the first time this is read is to fetch the value of the type property.
	var getType struct {
		Type string `json:"type"`
	}
	if err := consumer.Consume(buf, &getType); err != nil {
		return nil, err
	}

	if err := validate.RequiredString("type", "body", getType.Type); err != nil {
		return nil, err
	}

	// The value of type is used to determine which type to create and unmarshal the data into
	switch getType.Type {
	case "Geometry":
		var result geometry
		if err := consumer.Consume(buf2, &result); err != nil {
			return nil, err
		}
		return &result, nil
	case "Point":
		var result Point
		if err := consumer.Consume(buf2, &result); err != nil {
			return nil, err
		}
		return &result, nil
	}
	return nil, errors.New(422, "invalid type value: %q", getType.Type)
}

// Validate validates this geometry
func (m *geometry) Validate(formats strfmt.Registry) error {
	return nil
}
