// ----------------------------------------------------------------------------
// Code generated by `swagger generate operation`. DO NOT EDIT.
//
// See hack/generate-swagger-api.sh
// ----------------------------------------------------------------------------

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/go-openapi/loads"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage

	SpecDoc *loads.Document
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "The Teralytic API is served by the teralytic daemon. This api provides \nall of the services necessary for authorization and applications.\n\n# Authentication\n\nWith the exception of the authentication operations themselves (those tagged ` + "`" + `Auth` + "`" + `), all api\ncalls require a valid ` + "`" + `Bearer` + "`" + ` token in the HTTP ` + "`" + `Authorization` + "`" + ` header. The generation of these\ntokens is outside the spec of this document.\n\n# Versioning\n\nThis API supports versioning borrowed from the ` + "`" + `Docker` + "`" + ` project. Methods must be\ncalled with a version i.e (` + "`" + `/api/v2.0.0` + "`" + `). When a version change is made to an\noperation it will be noted in the CHANGELOG\n\n# Errors\n\nThe API uses standard HTTP status codes to indicate the success or failure\nof the API call. The body of the response will be JSON in the following\nformat:\n` + "`" + `` + "`" + `` + "`" + `\n{\n  \"message\": \"object not found\"\n}\n` + "`" + `` + "`" + `` + "`" + `\n",
    "title": "Teralytic API",
    "version": "2.0.0"
  },
  "basePath": "/api/v2.0.0",
  "paths": {
    "/properties": {
      "get": {
        "security": [
          {
            "OAuth": [
              "property:read"
            ]
          }
        ],
        "description": "Properties are physically distinct addressable locations.\n",
        "tags": [
          "Property"
        ],
        "operationId": "PropertyList",
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Property"
              }
            }
          },
          "400": {
            "description": "bad parameter",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "401": {
            "description": "unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Application": {
      "allOf": [
        {
          "description": "Applications are API clients that access APIs managed by the integration\nservice. Applications may provide user authentication flows.\n\nApplications are manage by the ` + "`" + `AuthController` + "`" + `.\n",
          "type": "object",
          "required": [
            "name",
            "allowed_grants"
          ],
          "properties": {
            "allowed_grants": {
              "description": "The applications allowed grant types",
              "type": "array",
              "items": {
                "type": "string",
                "enum": [
                  "authorization_code",
                  "client_credentials",
                  "refresh_token"
                ]
              }
            },
            "client_id": {
              "description": "The application client id used for oauth grants",
              "type": "string",
              "readOnly": true
            },
            "client_secret": {
              "description": "The application client secret used for oauth grants",
              "type": "string",
              "readOnly": true
            },
            "description": {
              "description": "The application description",
              "type": "string"
            },
            "login_uris": {
              "description": "This is an array of the application's allowed login uris. These are checked\nin the ` + "`" + `/authorize` + "`" + ` path to ensure the login redirect is allowed by the application.\n\nThis path on redirect will receive the following query parameters:\n  - ` + "`" + `auth_request` + "`" + `: An encoded and signed request value to be forwarded with the login post.\n",
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "logout_uris": {
              "description": "This is an array of the application's allowed logout uris. These are checked\nin the ` + "`" + `/logout` + "`" + ` path to ensure the logout redirect is allowed by the application.\n",
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "name": {
              "description": "The application name",
              "type": "string",
              "x-nullable": false
            },
            "permissions": {
              "description": "The application's authorized permissions",
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "redirect_uris": {
              "description": "This is an array of the application's allowed redirect uris. These are checked\nin the ` + "`" + `/login` + "`" + ` path to ensure the redirect is allowed by the application.\n\nThis path on redirect will receive the following query parameters:\n  - ` + "`" + `code` + "`" + `: A signed authorization code that can be passed to the ` + "`" + `/token` + "`" + ` path.\n",
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "token_lifetime": {
              "description": "The lifetime for identity tokens in seconds, provided the call requested the \n` + "`" + `openid` + "`" + ` scopes.\n",
              "type": "integer",
              "format": "int64"
            },
            "type": {
              "description": "The application type",
              "type": "string",
              "enum": [
                "web",
                "native",
                "machine"
              ]
            }
          }
        },
        {
          "type": "object",
          "properties": {
            "created_at": {
              "description": "The application creation date",
              "type": "string",
              "format": "date-time"
            },
            "id": {
              "description": "The application id",
              "type": "string"
            },
            "updated_at": {
              "description": "The last update date",
              "type": "string",
              "format": "date-time"
            }
          }
        }
      ]
    },
    "ErrorResponse": {
      "description": "A common error response",
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "description": "The error message",
          "type": "string",
          "x-nullable": false
        }
      }
    },
    "Geometry": {
      "description": "A geoJSON geometry",
      "type": "object",
      "required": [
        "type"
      ],
      "properties": {
        "type": {
          "description": "The geometry type",
          "type": "string",
          "enum": [
            "Point",
            "LineString",
            "Polygon",
            "MultiPoint",
            "MultiLineString",
            "MultiPolygon"
          ]
        }
      },
      "discriminator": "type"
    },
    "Point": {
      "description": "A geoJSON Point",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/Geometry"
        },
        {
          "properties": {
            "coordinates": {
              "$ref": "#/definitions/Point2D"
            }
          }
        }
      ]
    },
    "Point2D": {
      "type": "array",
      "maxItems": 2,
      "minItems": 2,
      "items": {
        "type": "number"
      }
    },
    "Property": {
      "description": "A property an addressable location owned by an organiztion",
      "type": "object",
      "required": [
        "Name"
      ],
      "properties": {
        "Address": {
          "description": "The property address in the format:\n\n  1234 Main St.\\n\n  Anwhere, PA 12345\\n\n",
          "type": "string"
        },
        "CreatedAt": {
          "description": "The property object creation time",
          "type": "string",
          "format": "date-time",
          "readOnly": true
        },
        "Id": {
          "description": "The property id",
          "type": "string",
          "readOnly": true
        },
        "Location": {
          "description": "The property location in lng,lat format",
          "$ref": "#/definitions/Point"
        },
        "Name": {
          "description": "The property name",
          "type": "string",
          "x-nullable": false
        },
        "UpdatedAt": {
          "description": "The property object update time",
          "type": "string",
          "format": "date-time",
          "readOnly": true
        }
      }
    },
    "User": {
      "allOf": [
        {
          "description": "A user is a user object\n",
          "type": "object",
          "required": [
            "login"
          ],
          "properties": {
            "login": {
              "description": "The user's login name",
              "type": "string",
              "x-nullable": false
            },
            "permissions": {
              "description": "The user's available permissions",
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "profile": {
              "$ref": "#/definitions/profile"
            }
          }
        },
        {
          "type": "object",
          "properties": {
            "created_at": {
              "description": "The user creation date",
              "type": "string",
              "format": "date-time"
            },
            "id": {
              "description": "The user id",
              "type": "string"
            },
            "metadata": {
              "description": "User metadata",
              "type": "object",
              "additionalProperties": {
                "type": "object"
              }
            },
            "updated_at": {
              "description": "The last update date",
              "type": "string",
              "format": "date-time"
            }
          }
        }
      ]
    },
    "address": {
      "description": "OpenID address claim as defined in section 5.1.1 of the connect core 1.0 specification",
      "type": "object",
      "properties": {
        "country": {
          "description": "Country name component.",
          "type": "string",
          "x-nullable": true
        },
        "formatted": {
          "description": "Full mailing address, formatted for display or use on a mailing label. This field MAY contain multiple lines, separated by newlines. \nNewlines can be represented either as a carriage return/line feed pair (\"\\r\\n\") or as a single line feed character (\"\\n\").\n",
          "type": "string",
          "x-nullable": true
        },
        "locality": {
          "description": "City or locality component.",
          "type": "string",
          "x-nullable": true
        },
        "postal_code": {
          "description": "Zip code or postal code component.",
          "type": "string",
          "x-nullable": true
        },
        "region": {
          "description": "State, province, prefecture, or region component.",
          "type": "string",
          "x-nullable": true
        },
        "street_address": {
          "description": "Full street address component, which MAY include house number, street name, Post Office Box, and multi-line extended street address \ninformation. This field MAY contain multiple lines, separated by newlines. Newlines can be represented either as a carriage return/line \nfeed pair (\"\\r\\n\") or as a single line feed character (\"\\n\").\n",
          "type": "string",
          "x-nullable": true
        }
      }
    },
    "profile": {
      "description": "A profile object based on the [openid connect standard](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims).\n",
      "type": "object",
      "required": [
        "sub"
      ],
      "properties": {
        "address": {
          "$ref": "#/definitions/address"
        },
        "birthdate": {
          "description": "End-User's birthday, represented as an ISO 8601:2004 [ISO8601‑2004] YYYY-MM-DD format. The year MAY be 0000, indicating that it is omitted. \nTo represent only the year, YYYY format is allowed. Note that depending on the underlying platform's date related function, providing just \nyear can result in varying month and day, so the implementers need to take this factor into account to correctly process the dates.\"\n",
          "type": "string",
          "format": "date",
          "x-nullable": true
        },
        "email": {
          "description": "The user's email address",
          "type": "string",
          "format": "email"
        },
        "email_verified": {
          "description": "True if the End-User's e-mail address has been verified; otherwise false. When this Claim Value is true, this means that the OP \ntook affirmative steps to ensure that this e-mail address was controlled by the End-User at the time the verification was performed. \nThe means by which an e-mail address is verified is context-specific, and dependent upon the trust framework or contractual agreements \nwithin which the parties are operating.\n",
          "type": "boolean"
        },
        "family_name": {
          "description": "Surname(s) or last name(s) of the End-User. Note that in some cultures, people can have multiple family names or no family name; \nall can be present, with the names being separated by space characters.\n",
          "type": "string"
        },
        "gender": {
          "description": "End-User's gender. Values defined by this specification are female and male. Other values MAY be used when neither \nof the defined values are applicable.\n",
          "type": "string"
        },
        "given_name": {
          "description": "Given name(s) or first name(s) of the End-User. Note that in some cultures, people can have multiple given names; \nall can be present, with the names being separated by space characters.\n",
          "type": "string"
        },
        "locale": {
          "description": "End-User's locale, represented as a BCP47 [RFC5646] language tag. This is typically an ISO 639-1 Alpha-2 [ISO639‑1] language code in lowercase \nand an ISO 3166-1 Alpha-2 [ISO3166‑1] country code in uppercase, separated by a dash. For example, en-US or fr-CA. As a compatibility note, \nsome implementations have used an underscore as the separator rather than a dash, for example, en_US; Relying Parties MAY choose to accept \nthis locale syntax as well.\n",
          "type": "string",
          "default": "en-US"
        },
        "middle_name": {
          "description": "Middle name(s) of the End-User. Note that in some cultures, people can have multiple middle names; \nall can be present, with the names being separated by space characters. Also note that in some cultures, middle names are not used.\n",
          "type": "string"
        },
        "name": {
          "description": "End-User's full name in displayable form including all name parts, possibly including titles and suffixes, \nordered according to the End-User's locale and preferences.\n",
          "type": "string"
        },
        "nickname": {
          "description": "Casual name of the End-User that may or may not be the same as the given_name. For instance, \na nickname value of Mike might be returned alongside a given_name value of Michael.\n",
          "type": "string"
        },
        "phone_number": {
          "description": "The user's phone number in E.164 format",
          "type": "string"
        },
        "phone_number_verified": {
          "description": "True if the End-User's phone number has been verified; otherwise false. When this Claim Value is true, this means that the OP \ntook affirmative steps to ensure that this phone number was controlled by the End-User at the time the verification was performed. \nThe means by which a phone number is verified is context-specific, and dependent upon the trust framework or contractual agreements \nwithin which the parties are operating. When true, the phone_number Claim MUST be in E.164 format and any extensions MUST be \nrepresented in RFC 3966 format.\"\n",
          "type": "boolean"
        },
        "picture": {
          "description": "URL of the End-User's profile picture. This URL MUST refer to an image file (for example, a PNG, JPEG, or GIF image file), \nrather than to a Web page containing an image. Note that this URL SHOULD specifically reference a profile photo of the \nEnd-User suitable for displaying when describing the End-User, rather than an arbitrary photo taken by the End-User.\n",
          "type": "string"
        },
        "preferred_username": {
          "description": "Shorthand name by which the End-User wishes to be referred to at the RP, such as janedoe or j.doe. This value MAY be any valid \nJSON string including special characters such as @, /, or whitespace. The RP MUST NOT rely upon this value being unique.\n",
          "type": "string"
        },
        "profile": {
          "description": "URL of the End-User's profile page. The contents of this Web page SHOULD be about the End-User.\n",
          "type": "string",
          "format": "uri"
        },
        "sub": {
          "description": "Subject - Identifier for the End-User at the Issuer.\n",
          "type": "string",
          "x-nullable": false
        },
        "updated_at": {
          "description": "Time the End-User's information was last updated. Its value is a JSON number representing the number of seconds from 1970-01-01T0:0:0Z\nas measured in UTC until the date/time.\n",
          "type": "integer",
          "format": "int64"
        },
        "website": {
          "description": "URL of the End-User's Web page or blog. This Web page SHOULD contain information published by the End-User or an \norganization that the End-User is affiliated with.\n",
          "type": "string"
        },
        "zoneinfo": {
          "description": "String from zoneinfo [zoneinfo] time zone database representing the End-User's time zone. For example, Europe/Paris or America/Los_Angeles.\n",
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "OAuth": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://auth.teralytic.io/oauth2/authorize",
      "tokenUrl": "https://auth.teralytic.io/oauth2/token",
      "scopes": {
        "property:read": "Ready properies"
      }
    }
  },
  "tags": [
    {
      "description": "Property methods are used to create and manage properties owned by the organization\n",
      "name": "Property"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "The Teralytic API is served by the teralytic daemon. This api provides \nall of the services necessary for authorization and applications.\n\n# Authentication\n\nWith the exception of the authentication operations themselves (those tagged ` + "`" + `Auth` + "`" + `), all api\ncalls require a valid ` + "`" + `Bearer` + "`" + ` token in the HTTP ` + "`" + `Authorization` + "`" + ` header. The generation of these\ntokens is outside the spec of this document.\n\n# Versioning\n\nThis API supports versioning borrowed from the ` + "`" + `Docker` + "`" + ` project. Methods must be\ncalled with a version i.e (` + "`" + `/api/v2.0.0` + "`" + `). When a version change is made to an\noperation it will be noted in the CHANGELOG\n\n# Errors\n\nThe API uses standard HTTP status codes to indicate the success or failure\nof the API call. The body of the response will be JSON in the following\nformat:\n` + "`" + `` + "`" + `` + "`" + `\n{\n  \"message\": \"object not found\"\n}\n` + "`" + `` + "`" + `` + "`" + `\n",
    "title": "Teralytic API",
    "version": "2.0.0"
  },
  "basePath": "/api/v2.0.0",
  "paths": {
    "/properties": {
      "get": {
        "security": [
          {
            "OAuth": [
              "property:read"
            ]
          }
        ],
        "description": "Properties are physically distinct addressable locations.\n",
        "tags": [
          "Property"
        ],
        "operationId": "PropertyList",
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Property"
              }
            }
          },
          "400": {
            "description": "bad parameter",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "401": {
            "description": "unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Application": {
      "allOf": [
        {
          "description": "Applications are API clients that access APIs managed by the integration\nservice. Applications may provide user authentication flows.\n\nApplications are manage by the ` + "`" + `AuthController` + "`" + `.\n",
          "type": "object",
          "required": [
            "name",
            "allowed_grants"
          ],
          "properties": {
            "allowed_grants": {
              "description": "The applications allowed grant types",
              "type": "array",
              "items": {
                "type": "string",
                "enum": [
                  "authorization_code",
                  "client_credentials",
                  "refresh_token"
                ]
              }
            },
            "client_id": {
              "description": "The application client id used for oauth grants",
              "type": "string",
              "readOnly": true
            },
            "client_secret": {
              "description": "The application client secret used for oauth grants",
              "type": "string",
              "readOnly": true
            },
            "description": {
              "description": "The application description",
              "type": "string"
            },
            "login_uris": {
              "description": "This is an array of the application's allowed login uris. These are checked\nin the ` + "`" + `/authorize` + "`" + ` path to ensure the login redirect is allowed by the application.\n\nThis path on redirect will receive the following query parameters:\n  - ` + "`" + `auth_request` + "`" + `: An encoded and signed request value to be forwarded with the login post.\n",
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "logout_uris": {
              "description": "This is an array of the application's allowed logout uris. These are checked\nin the ` + "`" + `/logout` + "`" + ` path to ensure the logout redirect is allowed by the application.\n",
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "name": {
              "description": "The application name",
              "type": "string",
              "x-nullable": false
            },
            "permissions": {
              "description": "The application's authorized permissions",
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "redirect_uris": {
              "description": "This is an array of the application's allowed redirect uris. These are checked\nin the ` + "`" + `/login` + "`" + ` path to ensure the redirect is allowed by the application.\n\nThis path on redirect will receive the following query parameters:\n  - ` + "`" + `code` + "`" + `: A signed authorization code that can be passed to the ` + "`" + `/token` + "`" + ` path.\n",
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "token_lifetime": {
              "description": "The lifetime for identity tokens in seconds, provided the call requested the \n` + "`" + `openid` + "`" + ` scopes.\n",
              "type": "integer",
              "format": "int64"
            },
            "type": {
              "description": "The application type",
              "type": "string",
              "enum": [
                "web",
                "native",
                "machine"
              ]
            }
          }
        },
        {
          "type": "object",
          "properties": {
            "created_at": {
              "description": "The application creation date",
              "type": "string",
              "format": "date-time"
            },
            "id": {
              "description": "The application id",
              "type": "string"
            },
            "updated_at": {
              "description": "The last update date",
              "type": "string",
              "format": "date-time"
            }
          }
        }
      ]
    },
    "ErrorResponse": {
      "description": "A common error response",
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "description": "The error message",
          "type": "string",
          "x-nullable": false
        }
      }
    },
    "Geometry": {
      "description": "A geoJSON geometry",
      "type": "object",
      "required": [
        "type"
      ],
      "properties": {
        "type": {
          "description": "The geometry type",
          "type": "string",
          "enum": [
            "Point",
            "LineString",
            "Polygon",
            "MultiPoint",
            "MultiLineString",
            "MultiPolygon"
          ]
        }
      },
      "discriminator": "type"
    },
    "Point": {
      "description": "A geoJSON Point",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/Geometry"
        },
        {
          "properties": {
            "coordinates": {
              "$ref": "#/definitions/Point2D"
            }
          }
        }
      ]
    },
    "Point2D": {
      "type": "array",
      "maxItems": 2,
      "minItems": 2,
      "items": {
        "type": "number"
      }
    },
    "Property": {
      "description": "A property an addressable location owned by an organiztion",
      "type": "object",
      "required": [
        "Name"
      ],
      "properties": {
        "Address": {
          "description": "The property address in the format:\n\n  1234 Main St.\\n\n  Anwhere, PA 12345\\n\n",
          "type": "string"
        },
        "CreatedAt": {
          "description": "The property object creation time",
          "type": "string",
          "format": "date-time",
          "readOnly": true
        },
        "Id": {
          "description": "The property id",
          "type": "string",
          "readOnly": true
        },
        "Location": {
          "description": "The property location in lng,lat format",
          "$ref": "#/definitions/Point"
        },
        "Name": {
          "description": "The property name",
          "type": "string",
          "x-nullable": false
        },
        "UpdatedAt": {
          "description": "The property object update time",
          "type": "string",
          "format": "date-time",
          "readOnly": true
        }
      }
    },
    "User": {
      "allOf": [
        {
          "description": "A user is a user object\n",
          "type": "object",
          "required": [
            "login"
          ],
          "properties": {
            "login": {
              "description": "The user's login name",
              "type": "string",
              "x-nullable": false
            },
            "permissions": {
              "description": "The user's available permissions",
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "profile": {
              "$ref": "#/definitions/profile"
            }
          }
        },
        {
          "type": "object",
          "properties": {
            "created_at": {
              "description": "The user creation date",
              "type": "string",
              "format": "date-time"
            },
            "id": {
              "description": "The user id",
              "type": "string"
            },
            "metadata": {
              "description": "User metadata",
              "type": "object",
              "additionalProperties": {
                "type": "object"
              }
            },
            "updated_at": {
              "description": "The last update date",
              "type": "string",
              "format": "date-time"
            }
          }
        }
      ]
    },
    "address": {
      "description": "OpenID address claim as defined in section 5.1.1 of the connect core 1.0 specification",
      "type": "object",
      "properties": {
        "country": {
          "description": "Country name component.",
          "type": "string",
          "x-nullable": true
        },
        "formatted": {
          "description": "Full mailing address, formatted for display or use on a mailing label. This field MAY contain multiple lines, separated by newlines. \nNewlines can be represented either as a carriage return/line feed pair (\"\\r\\n\") or as a single line feed character (\"\\n\").\n",
          "type": "string",
          "x-nullable": true
        },
        "locality": {
          "description": "City or locality component.",
          "type": "string",
          "x-nullable": true
        },
        "postal_code": {
          "description": "Zip code or postal code component.",
          "type": "string",
          "x-nullable": true
        },
        "region": {
          "description": "State, province, prefecture, or region component.",
          "type": "string",
          "x-nullable": true
        },
        "street_address": {
          "description": "Full street address component, which MAY include house number, street name, Post Office Box, and multi-line extended street address \ninformation. This field MAY contain multiple lines, separated by newlines. Newlines can be represented either as a carriage return/line \nfeed pair (\"\\r\\n\") or as a single line feed character (\"\\n\").\n",
          "type": "string",
          "x-nullable": true
        }
      }
    },
    "profile": {
      "description": "A profile object based on the [openid connect standard](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims).\n",
      "type": "object",
      "required": [
        "sub"
      ],
      "properties": {
        "address": {
          "$ref": "#/definitions/address"
        },
        "birthdate": {
          "description": "End-User's birthday, represented as an ISO 8601:2004 [ISO8601‑2004] YYYY-MM-DD format. The year MAY be 0000, indicating that it is omitted. \nTo represent only the year, YYYY format is allowed. Note that depending on the underlying platform's date related function, providing just \nyear can result in varying month and day, so the implementers need to take this factor into account to correctly process the dates.\"\n",
          "type": "string",
          "format": "date",
          "x-nullable": true
        },
        "email": {
          "description": "The user's email address",
          "type": "string",
          "format": "email"
        },
        "email_verified": {
          "description": "True if the End-User's e-mail address has been verified; otherwise false. When this Claim Value is true, this means that the OP \ntook affirmative steps to ensure that this e-mail address was controlled by the End-User at the time the verification was performed. \nThe means by which an e-mail address is verified is context-specific, and dependent upon the trust framework or contractual agreements \nwithin which the parties are operating.\n",
          "type": "boolean"
        },
        "family_name": {
          "description": "Surname(s) or last name(s) of the End-User. Note that in some cultures, people can have multiple family names or no family name; \nall can be present, with the names being separated by space characters.\n",
          "type": "string"
        },
        "gender": {
          "description": "End-User's gender. Values defined by this specification are female and male. Other values MAY be used when neither \nof the defined values are applicable.\n",
          "type": "string"
        },
        "given_name": {
          "description": "Given name(s) or first name(s) of the End-User. Note that in some cultures, people can have multiple given names; \nall can be present, with the names being separated by space characters.\n",
          "type": "string"
        },
        "locale": {
          "description": "End-User's locale, represented as a BCP47 [RFC5646] language tag. This is typically an ISO 639-1 Alpha-2 [ISO639‑1] language code in lowercase \nand an ISO 3166-1 Alpha-2 [ISO3166‑1] country code in uppercase, separated by a dash. For example, en-US or fr-CA. As a compatibility note, \nsome implementations have used an underscore as the separator rather than a dash, for example, en_US; Relying Parties MAY choose to accept \nthis locale syntax as well.\n",
          "type": "string",
          "default": "en-US"
        },
        "middle_name": {
          "description": "Middle name(s) of the End-User. Note that in some cultures, people can have multiple middle names; \nall can be present, with the names being separated by space characters. Also note that in some cultures, middle names are not used.\n",
          "type": "string"
        },
        "name": {
          "description": "End-User's full name in displayable form including all name parts, possibly including titles and suffixes, \nordered according to the End-User's locale and preferences.\n",
          "type": "string"
        },
        "nickname": {
          "description": "Casual name of the End-User that may or may not be the same as the given_name. For instance, \na nickname value of Mike might be returned alongside a given_name value of Michael.\n",
          "type": "string"
        },
        "phone_number": {
          "description": "The user's phone number in E.164 format",
          "type": "string"
        },
        "phone_number_verified": {
          "description": "True if the End-User's phone number has been verified; otherwise false. When this Claim Value is true, this means that the OP \ntook affirmative steps to ensure that this phone number was controlled by the End-User at the time the verification was performed. \nThe means by which a phone number is verified is context-specific, and dependent upon the trust framework or contractual agreements \nwithin which the parties are operating. When true, the phone_number Claim MUST be in E.164 format and any extensions MUST be \nrepresented in RFC 3966 format.\"\n",
          "type": "boolean"
        },
        "picture": {
          "description": "URL of the End-User's profile picture. This URL MUST refer to an image file (for example, a PNG, JPEG, or GIF image file), \nrather than to a Web page containing an image. Note that this URL SHOULD specifically reference a profile photo of the \nEnd-User suitable for displaying when describing the End-User, rather than an arbitrary photo taken by the End-User.\n",
          "type": "string"
        },
        "preferred_username": {
          "description": "Shorthand name by which the End-User wishes to be referred to at the RP, such as janedoe or j.doe. This value MAY be any valid \nJSON string including special characters such as @, /, or whitespace. The RP MUST NOT rely upon this value being unique.\n",
          "type": "string"
        },
        "profile": {
          "description": "URL of the End-User's profile page. The contents of this Web page SHOULD be about the End-User.\n",
          "type": "string",
          "format": "uri"
        },
        "sub": {
          "description": "Subject - Identifier for the End-User at the Issuer.\n",
          "type": "string",
          "x-nullable": false
        },
        "updated_at": {
          "description": "Time the End-User's information was last updated. Its value is a JSON number representing the number of seconds from 1970-01-01T0:0:0Z\nas measured in UTC until the date/time.\n",
          "type": "integer",
          "format": "int64"
        },
        "website": {
          "description": "URL of the End-User's Web page or blog. This Web page SHOULD contain information published by the End-User or an \norganization that the End-User is affiliated with.\n",
          "type": "string"
        },
        "zoneinfo": {
          "description": "String from zoneinfo [zoneinfo] time zone database representing the End-User's time zone. For example, Europe/Paris or America/Los_Angeles.\n",
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "OAuth": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://auth.teralytic.io/oauth2/authorize",
      "tokenUrl": "https://auth.teralytic.io/oauth2/token",
      "scopes": {
        "property:read": "Ready properies"
      }
    }
  },
  "tags": [
    {
      "description": "Property methods are used to create and manage properties owned by the organization\n",
      "name": "Property"
    }
  ]
}`))

	spec, err := loads.Analyzed(SwaggerJSON, "")
	if err != nil {
		panic(fmt.Errorf("analyze swagger: %v", err))
	}
	SpecDoc = spec
}
