# A Swagger 2.0 (a.k.a. OpenAPI) definition of the Teralytic API.
#
# This is used for generating API documentation and the types used by the
# client/server. See api/README.md for more information.
#
# Some style notes:
# - This file is used by ReDoc, which allows GitHub Flavored Markdown in
#   descriptions.
# - There is no maximum line length, for ease of editing and pretty diffs.
# - operationIds are in the format "NounVerb", with a singular noun.

swagger: "2.0"
schemes:
  - "http"
  - "https"
produces:
  - "application/json"
consumes:
  - "application/json"
basePath: "/api/v2.0.0"
info:
  title: "Teralytic API"
  version: "2.0.0"
  description: |
    The Teralytic API is served by the teralytic daemon. This api provides 
    all of the services necessary for authorization and applications.

    # Authentication

    With the exception of the authentication operations themselves (those tagged `Auth`), all api
    calls require a valid `Bearer` token in the HTTP `Authorization` header. The generation of these
    tokens is outside the spec of this document.

    # Versioning

    This API supports versioning borrowed from the `Docker` project. Methods must be
    called with a version i.e (`/api/v2.0.0`). When a version change is made to an
    operation it will be noted in the CHANGELOG

    # Errors

    The API uses standard HTTP status codes to indicate the success or failure
    of the API call. The body of the response will be JSON in the following
    format:
    ```
    {
      "message": "object not found"
    }
    ```

tags:
  - name: "Property"
    description: |
      Property methods are used to create and manage properties owned by the organization

securityDefinitions:
  OAuth:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://auth.teralytic.io/oauth2/authorize
    tokenUrl: https://auth.teralytic.io/oauth2/token
    scopes:
      property:read: Ready properies

definitions:
  Application:
    allOf:
      - $ref: "/go/src/github.com/Teralytic/oauth/api/swagger.yaml#/definitions/Application"
      - type: "object"
        properties:
          id:
            type: "string"
            description: "The application id"
          created_at:
            type: "string"
            description: "The application creation date"
            format: "date-time"
          updated_at:
            type: "string"
            description: "The last update date"
            format: "date-time"

  User:
    allOf:
      - $ref: "/go/src/github.com/Teralytic/oauth/api/swagger.yaml#/definitions/User"
      - type: "object"
        properties:
          id:
            type: "string"
            description: "The user id"
          metadata:
            type: "object"
            description: "User metadata"
            additionalProperties:
              type: "object"
          created_at:
            type: "string"
            description: "The user creation date"
            format: "date-time"
          updated_at:
            type: "string"
            description: "The last update date"
            format: "date-time"

  Property:
    description: "A property an addressable location owned by an organiztion"
    type: "object"
    required: ["Name"]
    properties:
      Id:
        type: "string"
        description: "The property id"
        readOnly: true
      Name:
        type: "string"
        description: "The property name"
        x-nullable: false
      Address:
        type: "string"
        description: |
          The property address in the format:

            1234 Main St.\n
            Anwhere, PA 12345\n
      Location:
        description: "The property location in lng,lat format"
        $ref: "#/definitions/Point"
      CreatedAt:
        type: "string"
        description: "The property object creation time"
        format: "date-time"
        readOnly: true
      UpdatedAt:
        type: "string"
        description: "The property object update time"
        format: "date-time"
        readOnly: true

  Geometry:
    type: "object"
    description: A geoJSON geometry
    discriminator: type
    required: ["type"]
    properties:
      type:
        type: "string"
        enum:
          - "Point"
          - "LineString"
          - "Polygon"
          - "MultiPoint"
          - "MultiLineString"
          - "MultiPolygon"
        description: "The geometry type"

  Point2D:
    type: "array"
    maxItems: 2
    minItems: 2
    items:
      type: "number"

  Point:
    type: object
    description: "A geoJSON Point"
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          coordinates:
            $ref: "#/definitions/Point2D"

  ErrorResponse:
    description: "A common error response"
    type: "object"
    required: ["message"]
    properties:
      message:
        type: "string"
        description: "The error message"
        x-nullable: false

paths:
  /properties:
    get:
      description: |
        Properties are physically distinct addressable locations.
      operationId: "PropertyList"
      tags: ["Property"]
      responses:
        200:
          description: "ok"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Property"
        400:
          description: "bad parameter"
          schema:
            $ref: "#/definitions/ErrorResponse"
        401:
          description: "unauthorized"
          schema:
            $ref: "#/definitions/ErrorResponse"
        500:
          description: "internal server error"
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
        - OAuth: ["property:read"]
