# A Swagger 2.0 (a.k.a. OpenAPI) definition of the API.
#
# This is used for generating API documentation and the types used by the
# client/server. See api/README.md for more information.
#
# Some style notes:
# - This file is used by ReDoc, which allows GitHub Flavored Markdown in
#   descriptions.
# - There is no maximum line length, for ease of editing and pretty diffs.
# - operationIds are in the format "NounVerb", with a singular noun.

swagger: "2.0"
schemes:
  - "http"
  - "https"
produces:
  - "application/json"
consumes:
  - "application/json"
basePath: "/api/v2.0.0"
info:
  title: "API"
  version: "2.0.0"
  description: |
    The API is served by the daemon. This api provides 
    all of the services necessary for authorization and applications.

    # Authentication

    With the exception of the authentication operations themselves (those tagged `Auth`), all api
    calls require a valid `Bearer` token in the HTTP `Authorization` header. The generation of these
    tokens is outside the spec of this document.

    # Versioning

    This API supports versioning borrowed from the `Docker` project. Methods must be
    called with a version i.e (`/api/v2.0.0`). When a version change is made to an
    operation it will be noted in the CHANGELOG

    # Errors

    The API uses standard HTTP status codes to indicate the success or failure
    of the API call. The body of the response will be JSON in the following
    format:
    ```
    {
      "message": "object not found"
    }
    ```

tags:
  - name: "Property"
    description: |
      Property methods are used to create and manage properties owned by the organization

securityDefinitions:
  OAuth:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://auth.server.local/oauth2/authorize
    tokenUrl: https://auth.server.local/oauth2/token
    scopes: {}

definitions:
  Application:
    allOf:
      - $ref: "/go/src/github.com/ModelRocket/oauth/api/swagger.yaml#/definitions/Application"
      - type: "object"
        properties:
          id:
            type: "string"
            description: "The application id"
          created_at:
            type: "string"
            description: "The application creation date"
            format: "date-time"
          updated_at:
            type: "string"
            description: "The last update date"
            format: "date-time"

  User:
    allOf:
      - $ref: "/go/src/github.com/ModelRocket/oauth/api/swagger.yaml#/definitions/User"
      - type: "object"
        properties:
          id:
            type: "string"
            description: "The user id"
          metadata:
            type: "object"
            description: "User metadata"
            additionalProperties:
              type: "object"
          created_at:
            type: "string"
            description: "The user creation date"
            format: "date-time"
          updated_at:
            type: "string"
            description: "The last update date"
            format: "date-time"

  ErrorResponse:
    description: "A common error response"
    type: "object"
    required: ["message"]
    properties:
      message:
        type: "string"
        description: "The error message"
        x-nullable: false

paths:
  /hello:
    get:
      description: "Hello World"
      tags: ["Greeting"]
      operationId: "HelloWorld"
      responses:
        200:
          description: "ok"
          schema:
            type: "string"
        400:
          description: "bad parameter"
          schema:
            $ref: "#/definitions/ErrorResponse"
        401:
          description: "unauthorized"
          schema:
            $ref: "#/definitions/ErrorResponse"
        500:
          description: "internal server error"
          schema:
            $ref: "#/definitions/ErrorResponse"
